In [9]:
import pandas as pd
import numpy as np

In [10]:
df_original = pd.read_csv('olist.csv')

In [11]:
df_original

,original_index,review_text,review_text_processed,review_text_tokenized,polarity,rating,kfold_polarity,kfold_rating
0,97262,Perfeito....chegou antes do prazo.....,perfeito....chegou antes do prazo.....,"['perfeito', 'chegou', 'antes', 'do', 'prazo']",1.0,5,1,1
1,72931,Foi uma ótima compra! Chegou antes mesmo do pr...,foi uma otima compra! chegou antes mesmo do pr...,"['foi', 'uma', 'otima', 'compra', 'chegou', 'a...",1.0,5,1,1
2,19659,Recebi muito rapido e um otimo custo beneficio,recebi muito rapido e um otimo custo beneficio,"['recebi', 'muito', 'rapido', 'um', 'otimo', '...",1.0,5,1,1
3,43054,Recomendo,recomendo,['recomendo'],1.0,5,1,1
4,59202,Só veio uma capa comprei 3 aí paguei. Mais de ...,so veio uma capa comprei 3 ai paguei. mais de ...,"['so', 'veio', 'uma', 'capa', 'comprei', 'ai',...",0.0,1,1,1
...,...,...,...,...,...,...,...,...
41739,49725,SUCESSO :D,sucesso :d,['sucesso'],1.0,5,10,10
41740,76794,Tudo OK. Produto entregue no prazo correto.,tudo ok. produto entregue no prazo correto.,"['tudo', 'ok', 'produto', 'entregue', 'no', 'p...",1.0,5,10,10
41741,72847,Ultimamente estão atrasando muito as entregas,ultimamente estao atrasando muito as entregas,"['ultimamente', 'estao', 'atrasando', 'muito',...",0.0,1,10,10
41742,50905,recomendo,recomendo,['recomendo'],1.0,5,10,10
41743,6468,A mascara veio com um pequeno defeito na estam...,a mascara veio com um pequeno defeito na estam...,"['mascara', 'veio', 'com', 'um', 'pequeno', 'd...",0.0,2,10,10

In [13]:
# Acessando a primeir linha da coluna review_text
df_original.iloc[1]['review_text']

'Foi uma ótima compra! Chegou antes mesmo do prazo e o produto é igual o que estava no anúncio. Correspondeu as expectativas!'

In [15]:
# Filtrar o DataFrame para colunas selecionadas
df = df_original[['review_text', 'review_text_processed', 'polarity']]
df

,review_text,review_text_processed,polarity
0,Perfeito....chegou antes do prazo.....,perfeito....chegou antes do prazo.....,1.0
1,Foi uma ótima compra! Chegou antes mesmo do pr...,foi uma otima compra! chegou antes mesmo do pr...,1.0
2,Recebi muito rapido e um otimo custo beneficio,recebi muito rapido e um otimo custo beneficio,1.0
3,Recomendo,recomendo,1.0
4,Só veio uma capa comprei 3 aí paguei. Mais de ...,so veio uma capa comprei 3 ai paguei. mais de ...,0.0
...,...,...,...
41739,SUCESSO :D,sucesso :d,1.0
41740,Tudo OK. Produto entregue no prazo correto.,tudo ok. produto entregue no prazo correto.,1.0
41741,Ultimamente estão atrasando muito as entregas,ultimamente estao atrasando muito as entregas,0.0
41742,recomendo,recomendo,1.0
41743,A mascara veio com um pequeno defeito na estam...,a mascara veio com um pequeno defeito na estam...,0.0

In [20]:
#### Normalizar capitalização
exemplo = 'EXCELENTE!! Valeu demais passar um tempo pesquisando preços, pois encontrei esse ótimo carregador de celular, nota 10.'
print ("Antes de normalizar: ")
print(exemplo)
exemplo = exemplo.lower()
print ("Depois de de normalizar: \n")
print(exemplo)

Antes de normalizar:
EXCELENTE!! Valeu demais passar um tempo pesquisando preços, pois encontrei esse ótimo carregador de celular, nota 10.
Depois de de normalizar:

excelente!! valeu demais passar um tempo pesquisando preços, pois encontrei esse ótimo carregador de celular, nota 10.